### ISSUE TITLE
Empty rdd throws an error while calling worker.train

### ISSUE THREAD

**Issue by ansrivas** [maxpumperla/elephas#1] opened 2015-08-25 11:34 UTC
Hi , thanks for writing elephas , looks very interesting.
I was just playing around with the code. 

I observed at some points  when the rdd is repartitioned , there might be empty partitions, they throw error in worker.train as keras tries to fit arrays with zero data.

**Comment by maxpumperla** [comment] 2015-09-14 14:21
Hi, Thanks for this! 

I noticed this, too, and think the problem is two-fold. First, in principle it should be OK to have partitions with zero data, although it's obviously not preferable. I have to look into how Spark does this exactly. 

Second, the actual error that's thrown comes down to a local Keras variable in Callbacks that is only initialized if there is data. Now, of course you wouldn't do this in Keras, but at least the error you get should be indicative of this.

I want to submit a proposal soon, which should then resolve the problem.

**Comment by ansrivas** [comment] 2015-09-14 14:38
I tried to check it as well, came up with something like this, may be you can verify this.
https://github.com/ansrivas/elephas/blob/master/elephas/spark_model.py#L51-L63

Couple of posts on stack-overflow also suggested that in rdd.mapPartition(func), func should take care of empty partitions.

**Comment by maxpumperla** [comment] 2015-09-14 15:09
Sure, that should do as quick fix. I'll integrate it later, thank you! Have to remember to check up on the Keras thing itself.

**Comment by maxpumperla** [comment] 2015-09-15 15:38
Turns out you have to make sure there's at least batch_size + 1 samples on each partition, so your check did not quite suffice. I submitted a fix and will close this now. Thanks again.

**Closed by maxpumperla** 2015-09-15 15:38 UTC
