### ISSUE TITLE
Support for python3 and Spark2

### ISSUE THREAD

**Issue by ErmiaAzarkhalili** [maxpumperla/elephas#33] opened 2016-11-12 03:58 UTC
Hi,
Could you please update your excellent package to support python 3 and Spark 2 as well. As I know you may utilize hyperas and hyperopt here; hence, updating all these packages would be great help for all people who extensively use them.

**Comment by maxpumperla** [comment] 2017-04-05 10:02
closing this, duplicate of #38 (py3 should be fine)

**Closed by maxpumperla** 2017-04-05 10:02 UTC
