### ISSUE TITLE
Can i use elephas to enhance the prediction ?

### ISSUE THREAD

**Issue by alaeddinechhima** [maxpumperla/elephas#55] opened 2017-08-23 14:52 UTC
I want to enhance prediction performance of my keras model so i am wondering if elephas could help me ?

**Comment by maxpumperla** [comment] 2018-08-15 13:37
closing as duplicate of #54

**Closed by maxpumperla** 2018-08-15 13:37 UTC

**Comment by danielenricocahall** [comment] 2021-01-19 02:25
Officially added support for parallel prediction and evaluation in 1.1.0: https://github.com/maxpumperla/elephas/releases/tag/1.1.0 feel free to play with it and let me know how it goes!
